version: '3.7'

services:
  postgres:
    container_name: 'examples.postgres'
    restart: always
    image: postgres
    build:
      context: ./
      dockerfile: postgres.dockerfile
    ports:
      - "5432:5432"
    volumes:
      - /usr/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_MULTIPLE_DATABASES=exampledb
    networks:
      - app_network
  app:
    container_name: 'shop.app'
    build:
      context: ../
      dockerfile: app.dockerfile
    ports:
      - "5000:5000"
    networks:
      - app_network  
  razor:
    container_name: 'shop.razor'
    build:
      context: ../
      dockerfile: razor.dockerfile
    ports:
      - "80:80"
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
    external: true
  