// <auto-generated />
using System;
using Database.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Database.EFCore.Migrations
{
    [DbContext(typeof(ExampleContext))]
    [Migration("20201117201648_DateToTimestamp")]
    partial class DateToTimestamp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Database.EFCore.Entities.SummaryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Summary");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Freezing"
                        },
                        new
                        {
                            Id = 2,
                            Code = "Bracing"
                        },
                        new
                        {
                            Id = 3,
                            Code = "Chilly"
                        },
                        new
                        {
                            Id = 4,
                            Code = "Cool"
                        },
                        new
                        {
                            Id = 5,
                            Code = "Mild"
                        },
                        new
                        {
                            Id = 6,
                            Code = "Warm"
                        },
                        new
                        {
                            Id = 7,
                            Code = "Balmy"
                        },
                        new
                        {
                            Id = 8,
                            Code = "Hot"
                        },
                        new
                        {
                            Id = 9,
                            Code = "Sweltering"
                        },
                        new
                        {
                            Id = 10,
                            Code = "Scorching"
                        });
                });

            modelBuilder.Entity("Database.EFCore.Entities.WeatherEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("SummaryId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("SummaryId");

                    b.ToTable("Weather");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SummaryId = 3,
                            Temperature = -1.3m,
                            TimeStamp = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            SummaryId = 5,
                            Temperature = 5.1m,
                            TimeStamp = new DateTime(2020, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            SummaryId = 1,
                            Temperature = -10m,
                            TimeStamp = new DateTime(2020, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Database.EFCore.Entities.WeatherEntity", b =>
                {
                    b.HasOne("Database.EFCore.Entities.SummaryEntity", "Summary")
                        .WithMany()
                        .HasForeignKey("SummaryId");
                });
#pragma warning restore 612, 618
        }
    }
}
