// <auto-generated />
using System;
using Database.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Database.EFCore.Migrations
{
    [DbContext(typeof(ExampleContext))]
    partial class ExampleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Database.EFCore.Entities.ShopCategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("shop_category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Supermarket"
                        },
                        new
                        {
                            Id = 2,
                            Code = "Petrol station"
                        },
                        new
                        {
                            Id = 3,
                            Code = "Toy shop"
                        });
                });

            modelBuilder.Entity("Database.EFCore.Entities.ShopEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric");                    
                    
                    b.Property<decimal>("Address")
                        .HasColumnType("text");            
                    
                    b.Property<decimal>("SiteLink")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("shop");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ShopCategoryEntity = 1,
                            Rating = 4.2,
                            Address = "test address",
                            SiteLink = "site.com"
                        });
                });

            modelBuilder.Entity("Database.EFCore.Entities.ShopEntity", b =>
                {
                    b.HasOne("Database.EFCore.Entities.ShopCategoryEntity", "shop_category")
                        .WithMany()
                        .HasForeignKey("CategoryId");
                });
        }
    }
}
